# Generated by Django 4.2.20 on 2025-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('revenue_type', models.TextField()),
                ('contractor', models.TextField()),
                ('contract_number', models.TextField()),
                ('sign_date', models.DateField()),
                ('subject', models.TextField()),
                ('code', models.TextField()),
                ('type', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'agrements.reestr',
                'managed': False,
            },
        ),
    ]
